PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# Checks existence of ID property and omschrijving of sbibliotheek

SELECT DISTINCT ?sbibliotheekURI ?id ?sbibliotheek ?omschrijving
WHERE {
  ?SymboolTopConcept a owl:Class .
  ?SymboolTopConcept skos:prefLabel "Symbool" .
  ?sbibliotheekURI rdfs:subClassOf ?SymboolTopConcept .
  ?sbibliotheekURI skos:prefLabel ?sbibliotheek .
  ?sbibliotheekURI skos:definition ?omschrijving .
  OPTIONAL {
    ?sbibliotheekURI ?idProperty ?id .
    ?idProperty skos:prefLabel "ID" .
  }
  FILTER((!BOUND(?id) || (STRLEN(STR(?id)) = 0) ) || (!BOUND(?omschrijving) || (STRLEN(STR(?omschrijving)) = 0) ))
} ORDER BY ?id 