PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# Check existence & availability of ?id ?code ?omschrijving ?verklaring

SELECT DISTINCT ?disciplineURI ?id ?code ?verklaring ?omschrijving
WHERE {
  ?DisciplineTopConcept skos:prefLabel "Disciplines" .
  ?disciplineURI a ?DisciplineTopConcept .
  ?disciplineURI skos:prefLabel ?code .
  ?disciplineURI skos:altLabel ?verklaring .
  ?disciplineURI skos:definition ?omschrijving .
  OPTIONAL {
    ?disciplineURI ?idProperty ?id .
    ?idProperty skos:prefLabel "ID" .
  }
  FILTER((!BOUND(?id) || (STRLEN(STR(?id)) = 0)) 
        || 
        (!BOUND(?code) || (STRLEN(STR(?code)) = 0)) 
        || 
        (!BOUND(?omschrijving) || (STRLEN(STR(?omschrijving)) = 0)) 
        || 
        (!BOUND(?verklaring) || (STRLEN(STR(?verklaring)) = 0))
        )
} ORDER BY ?id