;;*****************************************
;;  Nederlandse Cadstandaard NLCS  
;;  versie 2, feb 2010             
;;  Auteur: Nauk van der Donk      
;;                                 
;;*****************************************

*AVH-TEGEL_600X600_HALFST, Betontegels 60x60 halfsteensverband 
0.0 , 0.0  , 0.0  , 0.0, .6000
90.0, 0.0  , 0.0  , 0.0, .6000, .6000, -.6000
90.0, .30, .6000, 0.0, .6000, .6000, -.6000
