PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>

# Retrieves all Symbool information and stores it in the familiar Excel/CSV format

SELECT DISTINCT ?FASE ?BIB ?SYMBOOL ?ID
WHERE {
  ?SymboolTopConcept a owl:Class .
  ?SymboolTopConcept skos:prefLabel "Symbool" .
  ?Sbib rdfs:subClassOf ?SymboolTopConcept .
  ?Sbib skos:prefLabel ?BIB .
  ?Symbool rdfs:subClassOf* ?Sbib .
  ?Symbool skos:prefLabel ?SYMBOOL .
  FILTER (?Symbool != ?Sbib) .
  FILTER (CONTAINS(STR(?SYMBOOL), STR(CONCAT(STR(?BIB), "-")))) 
  OPTIONAL {
    BIND (STRBEFORE(STR(?SYMBOOL), STR(CONCAT(CONCAT("-", STR(?BIB)), "-" ))) AS ?FASE) .
  } OPTIONAL {
    ?Symbool ?IDProperty ?ID .
    ?IDProperty skos:prefLabel "ID" .
  }
} 