PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>

# Retrieves all Object information and stores it in the familiar Excel/CSV format from the SQL database

SELECT DISTINCT ?hoofdgroep ?id_nummer ?omschrijving ?kind_van ?status ?discipline
?lw_b ?kl_b ?kl_b_a ?kl_b_gd ?kl_b_gn ?kl_b_v ?lt_b
?lw_n ?kl_n ?kl_n_a ?kl_n_gd ?kl_n_gn ?kl_n_v ?lt_n
?lw_t ?kl_t ?kl_t_a ?kl_t_gd ?kl_t_gn ?kl_t_v ?lt_t
?lw_v ?kl_v ?kl_v_a ?kl_v_gd ?kl_v_gn ?kl_v_v ?lt_v
?element ?vrkl_kort
WHERE {
  ?NLCSObjectTopConcept a owl:Class .
  ?NLCSObjectTopConcept skos:prefLabel "NLCS-object" .
  ?hoofdgroepURI rdfs:subClassOf ?NLCSObjectTopConcept .
  ?hoofdgroepURI skos:prefLabel ?hoofdgroep .
  ?objectURI rdfs:subClassOf+ ?hoofdgroepURI .
  ?objectURI skos:prefLabel ?omschrijving .
  FILTER (?hoofdgroep = "AL") .  # INPUT REQUIRED - Change value to the desired hoofdgroep, AL is used as example
  OPTIONAL {
    ?objectURI ?idProperty ?id_nummer .
    ?idProperty skos:prefLabel "ID" .
  } 
  OPTIONAL {
    ?objectURI rdfs:subClassOf ?kind_vanURI .
    FILTER (?kind_vanURI != ?hoofdgroepURI) .
    ?kind_vanURI ?idProperty ?kind_van .
    ?idProperty skos:prefLabel "ID" .
  }
  OPTIONAL {
    ?objectURI ?elementProperty ?element .
    ?elementProperty skos:prefLabel "Element" .
  } 
  OPTIONAL {
    ?objectURI ?vrkl_kortProperty ?vrkl_kort .
    ?vrkl_kortProperty skos:prefLabel "VRKL_KORT" .
  } 

  ?objectURI rdfs:subClassOf ?bnodeStatus .
  ?bnodeStatus owl:onProperty ?StatusProperty .
  ?StatusProperty skos:prefLabel "Status" .
  OPTIONAL {
    ?bnodeStatus owl:hasValue/skos:prefLabel ?StatusValue .
  }
  BIND( COALESCE(?StatusValue, "*") AS ?status) .
  ?objectURI rdfs:subClassOf ?bnodeDiscipline .
  ?bnodeDiscipline owl:onProperty ?DisciplineProperty .
  ?DisciplineProperty skos:prefLabel "Discipline" .
  OPTIONAL {
    ?bnodeDiscipline owl:hasValue/skos:prefLabel ?DisciplineValue .
  }
  BIND( COALESCE(?DisciplineValue, "**") AS ?discipline) .

  OPTIONAL {
    ?objectURI ?elementProperty ?element .
    ?elementProperty skos:prefLabel "VRKL_KORT" .
  } 

  OPTIONAL {
    ?objectURI ?BLineweightProperty ?lw_bURI .
    ?BLineweightProperty skos:prefLabel "B lineweight" .
    ?lw_bURI skos:prefLabel ?lw_b .

    ?objectURI ?BColorProperty ?kl_bURI .
    ?BColorProperty skos:prefLabel "B color" .
    ?kl_bURI skos:prefLabel ?kl_b .

    ?objectURI ?BColorAProperty ?kl_b_aURI .
    ?BColorAProperty skos:prefLabel "B color A" .
    ?kl_b_aURI skos:prefLabel ?kl_b_a .

    ?objectURI ?BColorGDProperty ?kl_b_gdURI .
    ?BColorGDProperty skos:prefLabel "B color GD" .
    ?kl_b_gdURI skos:prefLabel ?kl_b_gd .

    ?objectURI ?BColorGNProperty ?kl_b_gnURI .
    ?BColorGNProperty skos:prefLabel "B color GN" .
    ?kl_b_gnURI skos:prefLabel ?kl_b_gn .

    ?objectURI ?BColorVProperty ?kl_b_vURI .
    ?BColorVProperty skos:prefLabel "B color V" .
    ?kl_b_vURI skos:prefLabel ?kl_b_v .

    ?objectURI ?BLinetypeProperty ?lt_bURI .
    ?BLinetypeProperty skos:prefLabel "B linetype" .
    ?lt_bURI skos:prefLabel ?lt_b .
  } 
  OPTIONAL {
    ?objectURI ?NLineweightProperty ?lw_nURI .
    ?NLineweightProperty skos:prefLabel "N lineweight" .
    ?lw_nURI skos:prefLabel ?lw_n .

    ?objectURI ?NColorProperty ?kl_nURI .
    ?NColorProperty skos:prefLabel "N color" .
    ?kl_nURI skos:prefLabel ?kl_n .

    ?objectURI ?NColorAProperty ?kl_n_aURI .
    ?NColorAProperty skos:prefLabel "N color A" .
    ?kl_n_aURI skos:prefLabel ?kl_n_a .

    ?objectURI ?NColorGDProperty ?kl_n_gdURI .
    ?NColorGDProperty skos:prefLabel "N color GD" .
    ?kl_n_gdURI skos:prefLabel ?kl_n_gd .

    ?objectURI ?NColorGNProperty ?kl_n_gnURI .
    ?NColorGNProperty skos:prefLabel "N color GN" .
    ?kl_n_gnURI skos:prefLabel ?kl_n_gn .

    ?objectURI ?NColorVProperty ?kl_n_vURI .
    ?NColorVProperty skos:prefLabel "N color V" .
    ?kl_n_vURI skos:prefLabel ?kl_n_v .

    ?objectURI ?NLinetypeProperty ?lt_nURI .
    ?NLinetypeProperty skos:prefLabel "N linetype" .
    ?lt_nURI skos:prefLabel ?lt_n .
  } 
  OPTIONAL {
    ?objectURI ?TLineweightProperty ?lw_tURI .
    ?TLineweightProperty skos:prefLabel "T lineweight" .
    ?lw_tURI skos:prefLabel ?lw_t .

    ?objectURI ?TColorProperty ?kl_tURI .
    ?TColorProperty skos:prefLabel "T color" .
    ?kl_tURI skos:prefLabel ?kl_t .

    ?objectURI ?TColorAProperty ?kl_t_aURI .
    ?TColorAProperty skos:prefLabel "T color A" .
    ?kl_t_aURI skos:prefLabel ?kl_t_a .

    ?objectURI ?TColorGDProperty ?kl_t_gdURI .
    ?TColorGDProperty skos:prefLabel "T color GD" .
    ?kl_t_gdURI skos:prefLabel ?kl_t_gd .

    ?objectURI ?TColorGNProperty ?kl_t_gnURI .
    ?TColorGNProperty skos:prefLabel "T color GN" .
    ?kl_t_gnURI skos:prefLabel ?kl_t_gn .

    ?objectURI ?TColorVProperty ?kl_t_vURI .
    ?TColorVProperty skos:prefLabel "T color V" .
    ?kl_t_vURI skos:prefLabel ?kl_t_v .

    ?objectURI ?TLinetypeProperty ?lt_tURI .
    ?TLinetypeProperty skos:prefLabel "T linetype" .
    ?lt_tURI skos:prefLabel ?lt_t .
  } 
  OPTIONAL {
    ?objectURI ?VLineweightProperty ?lw_vURI .
    ?VLineweightProperty skos:prefLabel "V lineweight" .
    ?lw_vURI skos:prefLabel ?lw_v .

    ?objectURI ?VColorProperty ?kl_vURI .
    ?VColorProperty skos:prefLabel "V color" .
    ?kl_vURI skos:prefLabel ?kl_v .

    ?objectURI ?VColorAProperty ?kl_v_aURI .
    ?VColorAProperty skos:prefLabel "V color A" .
    ?kl_v_aURI skos:prefLabel ?kl_v_a .

    ?objectURI ?VColorGDProperty ?kl_v_gdURI .
    ?VColorGDProperty skos:prefLabel "V color GD" .
    ?kl_v_gdURI skos:prefLabel ?kl_v_gd .

    ?objectURI ?VColorGNProperty ?kl_v_gnURI .
    ?VColorGNProperty skos:prefLabel "V color GN" .
    ?kl_v_gnURI skos:prefLabel ?kl_v_gn .

    ?objectURI ?VColorVProperty ?kl_v_vURI .
    ?VColorVProperty skos:prefLabel "V color V" .
    ?kl_v_vURI skos:prefLabel ?kl_v_v .

    ?objectURI ?VLinetypeProperty ?lt_vURI .
    ?VLinetypeProperty skos:prefLabel "V linetype" .
    ?lt_vURI skos:prefLabel ?lt_v .
  } 
  
} ORDER BY ?id
