PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>

# Retrieves all Symbool information and stores it in the familiar Excel/CSV format

SELECT DISTINCT ?FASE ?sBIB ?SYMBOOL ?SYMBOOL_alt ?ID ?opt ?STATUS ?VRKL_KORT ?VRKL_LANG
WHERE {
  ?SymboolTopConcept a owl:Class .
  ?SymboolTopConcept skos:prefLabel "Symbool" .
  ?Sbib rdfs:subClassOf ?SymboolTopConcept .
  ?Sbib skos:prefLabel ?sBIB .
  ?Symbool rdfs:subClassOf+ ?Sbib .
  ?Symbool skos:prefLabel ?SYMBOOL .
  optional { ?Symbool skos:altLabel ?SYMBOOL_alt . }
  optional {
  ?Symbool rdfs:subClassOf ?bnodeStatus .
  ?bnodeStatus owl:onProperty ?StatusProperty .
  ?StatusProperty skos:prefLabel "Status" .
  OPTIONAL {    ?StatusProperty owl:hasValue/skos:prefLabel ?StatusValue .  }
    }
  BIND( COALESCE(?StatusValue, "*") AS ?STATUS) .  
  FILTER (CONTAINS(STR(?SYMBOOL), STR(CONCAT(STR(?sBIB), "-")))) 
  OPTIONAL {
    BIND (STRBEFORE(STR(?SYMBOOL), STR(CONCAT(CONCAT("-", STR(?sBIB)), "-" ))) AS ?FASE2) . 
        bind (if(contains(?FASE2,"-"),strbefore(?FASE2,"-"),?FASE2) as ?FASE) }
    optional {
  bind ( strafter(?SYMBOOL,CONCAT(STR(?sBIB),"-")) as ?opt2) 
  bind ( if ( contains(?opt2,"-"),strafter(?opt2,"-"),?opt2) as ?opt3 )
  bind ( if ( contains(?opt3,"-"),strafter(?opt3,"-"),?opt3) as ?opt4 )
  bind ( if (strlen(?opt4)>4,"",?opt4) as ?opt )
  } 
        OPTIONAL {
    ?Symbool ?IDProperty ?ID .
    ?IDProperty skos:prefLabel "ID" .
  }
    OPTIONAL {
    ?Symbool ?VRKL_KORTProperty ?VRKL_KORT .
    ?VRKL_KORTProperty skos:prefLabel "VRKL_KORT" .
  } 
        OPTIONAL {
    ?Symbool ?VRKL_LANGProperty ?VRKL_LANG .
    ?VRKL_LANGProperty skos:prefLabel "VRKL_LANG" .
  }
}