PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>

SELECT DISTINCT ?FASE ?BIB ?ARCERING ?opt ?Arcering ?ID ?VRKL_KORT ?VRKL_LANG 
WHERE {
  ?ArceringTopConcept a owl:Class .
  ?ArceringTopConcept skos:prefLabel "Arcering" .
  ?Abib rdfs:subClassOf ?ArceringTopConcept .
  ?Abib skos:prefLabel ?BIB .
  ?Arcering rdfs:subClassOf+ ?Abib .
  ?Arcering skos:prefLabel ?ARCERING .
  FILTER (CONTAINS(STR(?ARCERING), STR(CONCAT(STR(?BIB), "-")))) 
  OPTIONAL {
    BIND (STRBEFORE(STR(?ARCERING), STR(CONCAT(CONCAT("-", STR(?BIB)), "-" ))) AS ?FASE) .
    OPTIONAL { BIND ( STRAFTER(SUBSTR(?ARCERING,5), "-") AS ?opt) }
  } 
  OPTIONAL {
    ?Arcering ?IDProperty ?ID .
    ?IDProperty skos:prefLabel "ID" .
  } 
  OPTIONAL {
    ?Arcering ?VRKL_KORTProperty ?VRKL_KORT .
    ?VRKL_KORTProperty skos:prefLabel "VRKL_KORT" .
  } 
  OPTIONAL {
    ?Arcering ?VRKL_LANGProperty ?VRKL_LANG .
    ?VRKL_LANGProperty skos:prefLabel "VRKL_LANG" .
  } 
}
