PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX nen2660: <https://w3id.org/nen2660/def#>

# Retrieves the mapping of the GWSW concept combination to the NLCS objects and symbols
# NOTE: Requires the NLCS publication to be added as default-graph-uri

SELECT ?mappingElement ?gwswStelselType ?gwswType ?nlcsObject ?nlcsObjectName ?nlcsSymbool ?nlcsSymbolName
WHERE {
  ?mappingElement nen2660:isPartOf ?gwswStelselType .
  ?mappingElement ?gwswTypeProperty ?gwswType .
  ?gwswTypeProperty skos:prefLabel "has GWSW type" .
  
  ?mappingElement ?nlcsObjectProperty ?nlcsObject .
  ?nlcsObjectProperty skos:prefLabel "has NLCS object" .
  ?nlcsObject skos:prefLabel ?nlcsObjectName .  # From NLCS publication
  
  OPTIONAL {
    ?mappingElement ?nlcsSymbolProperty ?nlcsSymbol .
    ?nlcsSymbolProperty skos:prefLabel "has NLCS symbol" .
    ?nlcsSymbol skos:prefLabel ?nlcsSymbolName .  # From NLCS publication
  }
}