PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX nen2660: <https://w3id.org/nen2660/def#>

SELECT ?physicalObject ?physicalObjectName
WHERE {
  ?physicalObject a owl:Class .
  ?physicalObject rdfs:subClassOf+ nen2660:RealObject .
  FILTER (CONTAINS(STR(?physicalObject),"http://digitalbuildingdata.tech/nlcs-class/"))
  ?physicalObject skos:prefLabel ?physicalObjectName .
  FILTER ( ?physicalObjectName NOT IN ("actor"@nl, "agent"@en))

  FILTER NOT EXISTS {
    ?stelsel a owl:Class .
    ?stelsel rdfs:subClassOf ?partRestriction .
    ?partRestriction owl:onProperty nen2660:hasPart .
    ?partRestriction owl:onClass ?physicalObject .
  }

}