PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX nen2660: <https://w3id.org/nen2660/def#>

# NOTE: Haalt alleen aspecten en bijbehorende waardelijsten die worden toegepast bij concepten

SELECT DISTINCT ?aspect ?aspectName ?waardelijst 
WHERE {
  ?waardelijst a owl:Class .
  ?waardelijst rdfs:subClassOf nen2660:EnumerationType .
  FILTER (CONTAINS(STR(?waardelijst),"http://digitalbuildingdata.tech/nlcs-class/"))

  ?bnodeAspect sh:class ?waardelijst .
  ?bnodeAspect sh:path ?aspect .
  ?aspect skos:prefLabel ?aspectName .

}