PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>

# Retrieves all Object information and stores it in the familiar Excel/CSV format from the SQL database

SELECT DISTINCT ?objectURI ?hoofdgroepURI ?hoofdgroep ?id_nummer ?omschrijving ?kind_vanURI ?kind_van ?status ?discipline
?lw_bURI ?lw_b ?kl_bURI ?kl_b ?kl_b_aURI ?kl_b_a ?kl_b_gdURI ?kl_b_gd ?kl_b_gnURI ?kl_b_gn ?kl_b_vURI ?kl_b_v ?lt_bURI ?lt_b
?lw_nURI ?lw_n ?kl_nURI ?kl_n ?kl_n_aURI ?kl_n_a ?kl_n_gdURI ?kl_n_gd ?kl_n_gnURI ?kl_n_gn ?kl_n_vURI ?kl_n_v ?lt_nURI ?lt_n
?lw_tURI ?lw_t ?kl_tURI ?kl_t ?kl_t_aURI ?kl_t_a ?kl_t_gdURI ?kl_t_gd ?kl_t_gnURI ?kl_t_gn ?kl_t_vURI ?kl_t_v ?lt_tURI ?lt_t
?lw_vURI ?lw_v ?kl_vURI ?kl_v ?kl_v_aURI ?kl_v_a ?kl_v_gdURI ?kl_v_gd ?kl_v_gnURI ?kl_v_gn ?kl_v_vURI ?kl_v_v ?lt_vURI ?lt_v
?element ?sobjectURI ?sobject ?aobjectURI ?aobject ?vrkl_kort
WHERE {
  ?NLCSObjectTopConcept a owl:Class .
  ?NLCSObjectTopConcept skos:prefLabel "NLCS-object" .
  ?hoofdgroepURI rdfs:subClassOf ?NLCSObjectTopConcept .
  ?hoofdgroepURI skos:prefLabel ?hoofdgroep .
  ?objectURI rdfs:subClassOf+ ?hoofdgroepURI .
  ?objectURI skos:prefLabel ?omschrijving .
  FILTER (?hoofdgroep = "AL") .  # INPUT REQUIRED - Change value to the desired hoofdgroep, AL is used as example
  OPTIONAL {
    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/b718adec73e04ce3ec720dd11a06a308> ?id_nummer .  # ?objectURI ?idProperty ?id_nummer . ?idProperty skos:prefLabel "ID" .
  } 
  OPTIONAL {
    ?objectURI rdfs:subClassOf ?kind_vanURI .
    FILTER (?kind_vanURI != ?hoofdgroepURI) .
    ?kind_vanURI <http://digitalbuildingdata.tech/nlcs/def/b718adec73e04ce3ec720dd11a06a308> ?kind_van .  # ?kind_vanURI ?idProperty ?kind_van . ?idProperty skos:prefLabel "ID" .
  }
  OPTIONAL {
    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/231afe47f3f37d3808096b36c28b4ded> ?element .  # ?objectURI ?elementProperty ?element . ?elementProperty skos:prefLabel "Element" .
  } 
  OPTIONAL {
    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/9c241815bb021ad8b7146ffb88dcf856> ?vrkl_kort .  # ?objectURI ?vrkl_kortProperty ?vrkl_kort . ?vrkl_kortProperty skos:prefLabel "VRKL_KORT" .
  } 
  OPTIONAL {
    ?objectURI rdfs:subClassOf ?bnodeStatus .
    ?bnodeStatus owl:onProperty <http://digitalbuildingdata.tech/nlcs/def/580a54a5-3f8e-4d92-afac-24eb23707884> .  # ?bnodeStatus owl:onProperty ?StatusProperty . ?StatusProperty skos:prefLabel "Status" .
    OPTIONAL {
      ?bnodeStatus owl:hasValue/skos:prefLabel ?StatusValue .
    }
    BIND( COALESCE(?StatusValue, "*") AS ?status) .
  }
  OPTIONAL {
    ?objectURI rdfs:subClassOf ?bnodeDiscipline .
    ?bnodeDiscipline owl:onProperty <http://digitalbuildingdata.tech/nlcs/def/d01031dc-9abe-47d3-9656-17185c986709> .  # ?bnodeDiscipline owl:onProperty ?DisciplineProperty . ?DisciplineProperty skos:prefLabel "Discipline" . 
    OPTIONAL {
      ?bnodeDiscipline owl:hasValue/skos:prefLabel ?DisciplineValue .
    }
    BIND( COALESCE(?DisciplineValue, "**") AS ?discipline) .
  }
  OPTIONAL {
    ?objectURI rdfs:subClassOf ?bnodeSymbool .
    ?bnodeSymbool owl:onProperty <https://w3id.org/nen2660/def#isDescribedBy> .
    ?bnodeSymbool owl:onClass ?sobjectURI .
    ?sobjectURI rdfs:subClassOf* ?SymboolTopConcept .
    ?SymboolTopConcept skos:prefLabel "Symbool" .
    ?sobjectURI skos:prefLabel ?sobject .
  }
  OPTIONAL {
    ?objectURI rdfs:subClassOf ?bnodeArcering .
    ?bnodeArcering owl:onProperty <https://w3id.org/nen2660/def#isDescribedBy> .
    ?bnodeArcering owl:onClass ?aobjectURI .
    ?aobjectURI rdfs:subClassOf* ?ArceringTopConcept .
    ?ArceringTopConcept skos:prefLabel "Arcering" .
    ?aobjectURI skos:prefLabel ?aobject .
  }

  OPTIONAL {
    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/f0ae4b93e35441578842bc4fd8709956> ?lw_bURI .  # ?objectURI ?BLineweightProperty ?lw_bURI . ?BLineweightProperty skos:prefLabel "B lineweight" .
    ?lw_bURI skos:prefLabel ?lw_b .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/2e7b1dc3283e79482dc1153895dbf149> ?kl_bURI_temp .  # ?objectURI ?BColorProperty ?kl_bURI_temp . ?BColorProperty skos:prefLabel "B color" .
    OPTIONAL {
      ?kl_bURI_temp skos:prefLabel ?kl_b_temp .
    }
    BIND( COALESCE(?kl_b_temp, ?kl_bURI_temp) AS ?kl_b) .
    BIND( IF(?kl_b = ?kl_b_temp, ?kl_bURI_temp, ?undefined) AS ?kl_bURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/3f9a348f67332197fd0bbbeda98e4358> ?kl_b_aURI_temp .  # ?objectURI ?BColorAProperty ?kl_b_aURI_temp . ?BColorAProperty skos:prefLabel "B color A" .
    OPTIONAL {
      ?kl_b_aURI_temp skos:prefLabel ?kl_b_a_temp .
    }
    BIND( COALESCE(?kl_b_a_temp, ?kl_b_aURI_temp) AS ?kl_b_a) .
    BIND( IF(?kl_b_a = ?kl_b_a_temp, ?kl_b_aURI_temp, ?undefined) AS ?kl_b_aURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/070e6b1e670a6f704021f47dfb916561> ?kl_b_gdURI_temp .  # ?objectURI ?BColorGDProperty ?kl_b_gdURI_temp . ?BColorGDProperty skos:prefLabel "B color GD" .
    OPTIONAL {
      ?kl_b_gdURI_temp skos:prefLabel ?kl_b_gd_temp .
    }
    BIND( COALESCE(?kl_b_gd_temp, ?kl_b_gdURI_temp) AS ?kl_b_gd) .
    BIND( IF(?kl_b_gd = ?kl_b_gd_temp, ?kl_b_gdURI_temp, ?undefined) AS ?kl_b_gdURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/1837b3cbc76cf5be8bf2919440cffc1a> ?kl_b_gnURI_temp .  # ?objectURI ?BColorGNProperty ?kl_b_gnURI_temp . ?BColorGNProperty skos:prefLabel "B color GN" .
    OPTIONAL {
      ?kl_b_gnURI_temp skos:prefLabel ?kl_b_gn_temp .
    }
    BIND( COALESCE(?kl_b_gn_temp, ?kl_b_gnURI_temp) AS ?kl_b_gn) .
    BIND( IF(?kl_b_gn = ?kl_b_gn_temp, ?kl_b_gnURI_temp, ?undefined) AS ?kl_b_gnURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/e6a1db6908635962b1da9e1230718656> ?kl_b_vURI_temp .  # ?objectURI ?BColorVProperty ?kl_b_vURI_temp . ?BColorVProperty skos:prefLabel "B color V" .
    OPTIONAL {
      ?kl_b_vURI_temp skos:prefLabel ?kl_b_v_temp .
    }
    BIND( COALESCE(?kl_b_v_temp, ?kl_b_vURI_temp) AS ?kl_b_v) .
    BIND( IF(?kl_b_v = ?kl_b_v_temp, ?kl_b_vURI_temp, ?undefined) AS ?kl_b_vURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/99271b8e4692f59ed33a550afaf542ac> ?lt_bURI .  # ?objectURI ?BLinetypeProperty ?lt_bURI . ?BLinetypeProperty skos:prefLabel "B linetype" .
    ?lt_bURI skos:prefLabel ?lt_b .
  } 
  OPTIONAL {
    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/0f2b46296496d5476b4e94d885d2d6ad> ?lw_nURI .  # ?objectURI ?NLineweightProperty ?lw_nURI . ?NLineweightProperty skos:prefLabel "N lineweight" .
    ?lw_nURI skos:prefLabel ?lw_n .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/99c67830d90d074c22802a459c856f4c> ?kl_nURI_temp .  # ?objectURI ?NColorProperty ?kl_nURI_temp . ?NColorProperty skos:prefLabel "N color" .
    OPTIONAL {
      ?kl_nURI_temp skos:prefLabel ?kl_n_temp .
    }
    BIND( COALESCE(?kl_n_temp, ?kl_nURI_temp) AS ?kl_n) .
    BIND( IF(?kl_n = ?kl_n_temp, ?kl_nURI_temp, ?undefined) AS ?kl_nURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/3f9c82ae0acc677b43f9c55db4c67d91> ?kl_n_aURI_temp .  # ?objectURI ?NColorAProperty ?kl_n_aURI_temp . ?NColorAProperty skos:prefLabel "N color A" .
    OPTIONAL {
      ?kl_n_aURI_temp skos:prefLabel ?kl_n_a_temp .
    }
    BIND( COALESCE(?kl_n_a_temp, ?kl_n_aURI_temp) AS ?kl_n_a) .
    BIND( IF(?kl_n_a = ?kl_n_a_temp, ?kl_n_aURI_temp, ?undefined) AS ?kl_n_aURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/964528fb003559383e99b63fca2b72e5> ?kl_n_gdURI_temp .  # ?objectURI ?NColorGDProperty ?kl_n_gdURI_temp . ?NColorGDProperty skos:prefLabel "N color GD" .
    OPTIONAL {
      ?kl_n_gdURI_temp skos:prefLabel ?kl_n_gd_temp .
    }
    BIND( COALESCE(?kl_n_gd_temp, ?kl_n_gdURI_temp) AS ?kl_n_gd) .
    BIND( IF(?kl_n_gd = ?kl_n_gd_temp, ?kl_n_gdURI_temp, ?undefined) AS ?kl_n_gdURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/a756b1013ec00304b3694f72789f5489> ?kl_n_gnURI_temp .  # ?objectURI ?NColorGNProperty ?kl_n_gnURI_temp . ?NColorGNProperty skos:prefLabel "N color GN" .
    OPTIONAL {
      ?kl_n_gnURI_temp skos:prefLabel ?kl_n_gn_temp .
    }
    BIND( COALESCE(?kl_n_gn_temp, ?kl_n_gnURI_temp) AS ?kl_n_gn) .
    BIND( IF(?kl_n_gn = ?kl_n_gn_temp, ?kl_n_gnURI_temp, ?undefined) AS ?kl_n_gnURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/7b9b57ab5cd1409412c9c21aa8a75be0> ?kl_n_vURI_temp .  # ?objectURI ?NColorVProperty ?kl_n_vURI_temp . ?NColorVProperty skos:prefLabel "N color V" .
    OPTIONAL {
      ?kl_n_vURI_temp skos:prefLabel ?kl_n_v_temp .
    }
    BIND( COALESCE(?kl_n_v_temp, ?kl_n_vURI_temp) AS ?kl_n_v) .
    BIND( IF(?kl_n_v = ?kl_n_v_temp, ?kl_n_vURI_temp, ?undefined) AS ?kl_n_vURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/fffb63ae8b6d147830578bf41ba4bfa3> ?lt_nURI .  # ?objectURI ?NLinetypeProperty ?lt_nURI . ?NLinetypeProperty skos:prefLabel "N linetype" .
    ?lt_nURI skos:prefLabel ?lt_n .
  } 
  OPTIONAL {
    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/44d44b47e72154e00a246fe6d5ae90df> ?lw_tURI .  # ?objectURI ?TLineweightProperty ?lw_tURI . ?TLineweightProperty skos:prefLabel "T lineweight" .
    ?lw_tURI skos:prefLabel ?lw_t .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/3d9494010633141738dac4db0d4371bd> ?kl_tURI_temp .  # ?objectURI ?TColorProperty ?kl_tURI_temp . ?TColorProperty skos:prefLabel "T color" .
    OPTIONAL {
      ?kl_tURI_temp skos:prefLabel ?kl_t_temp .
    }
    BIND( COALESCE(?kl_t_temp, ?kl_tURI_temp) AS ?kl_t) .
    BIND( IF(?kl_t = ?kl_t_temp, ?kl_tURI_temp, ?undefined) AS ?kl_tURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/f15cb56f17b45c122093acb2f6ef2666> ?kl_t_aURI_temp .  # ?objectURI ?TColorAProperty ?kl_t_aURI_temp . ?TColorAProperty skos:prefLabel "T color A" .
    OPTIONAL {
      ?kl_t_aURI_temp skos:prefLabel ?kl_t_a_temp .
    }
    BIND( COALESCE(?kl_t_a_temp, ?kl_t_aURI_temp) AS ?kl_t_a) .
    BIND( IF(?kl_t_a = ?kl_t_a_temp, ?kl_t_aURI_temp, ?undefined) AS ?kl_t_aURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/11a56ac7445d51fa54dbbb4977a950b1> ?kl_t_gdURI_temp .  # ?objectURI ?TColorGDProperty ?kl_t_gdURI_temp . ?TColorGDProperty skos:prefLabel "T color GD" .
    OPTIONAL {
      ?kl_t_gdURI_temp skos:prefLabel ?kl_t_gd_temp .
    }
    BIND( COALESCE(?kl_t_gd_temp, ?kl_t_gdURI_temp) AS ?kl_t_gd) .
    BIND( IF(?kl_t_gd = ?kl_t_gd_temp, ?kl_t_gdURI_temp, ?undefined) AS ?kl_t_gdURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/6fabaa692ad70ad1e62b2ed2d3e0b240> ?kl_t_gnURI_temp .  # ?objectURI ?TColorGNProperty ?kl_t_gnURI_temp . ?TColorGNProperty skos:prefLabel "T color GN" .
    OPTIONAL {
      ?kl_t_gnURI_temp skos:prefLabel ?kl_t_gn_temp .
    }
    BIND( COALESCE(?kl_t_gn_temp, ?kl_t_gnURI_temp) AS ?kl_t_gn) .
    BIND( IF(?kl_t_gn = ?kl_t_gn_temp, ?kl_t_gnURI_temp, ?undefined) AS ?kl_t_gnURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/9d31195f1dd92f368d648425fd92ddbc> ?kl_t_vURI_temp .  # ?objectURI ?TColorVProperty ?kl_t_vURI_temp . ?TColorVProperty skos:prefLabel "T color V" .
    OPTIONAL {
      ?kl_t_vURI_temp skos:prefLabel ?kl_t_v_temp .
    }
    BIND( COALESCE(?kl_t_v_temp, ?kl_t_vURI_temp) AS ?kl_t_v) .
    BIND( IF(?kl_t_v = ?kl_t_v_temp, ?kl_t_vURI_temp, ?undefined) AS ?kl_t_vURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/5f36dd80a4a3f96ed76158ec5d420be7> ?lt_tURI .  # ?objectURI ?TLinetypeProperty ?lt_tURI . ?TLinetypeProperty skos:prefLabel "T linetype" .
    ?lt_tURI skos:prefLabel ?lt_t .
  }  
  OPTIONAL {
    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/35efcfbbb79075b1eec92ae2a5ec744d> ?lw_vURI .  # ?objectURI ?VLineweightProperty ?lw_vURI . ?VLineweightProperty skos:prefLabel "V lineweight" .
    ?lw_vURI skos:prefLabel ?lw_v .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/641531752f6d7d9c46654b91db0f8ecd> ?kl_vURI_temp .  # ?objectURI ?VColorProperty ?kl_vURI_temp . ?VColorProperty skos:prefLabel "V color" .
    OPTIONAL {
      ?kl_vURI_temp skos:prefLabel ?kl_v_temp .
    }
    BIND( COALESCE(?kl_v_temp, ?kl_vURI_temp) AS ?kl_v) .
    BIND( IF(?kl_v = ?kl_v_temp, ?kl_vURI_temp, ?undefined) AS ?kl_vURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/dde96840a10d858e2d5a63d22b0c95a3> ?kl_v_aURI_temp .  # ?objectURI ?VColorAProperty ?kl_v_aURI_temp . ?VColorAProperty skos:prefLabel "V color A" .
    OPTIONAL {
      ?kl_v_aURI_temp skos:prefLabel ?kl_v_a_temp .
    }
    BIND( COALESCE(?kl_v_a_temp, ?kl_v_aURI_temp) AS ?kl_v_a) .
    BIND( IF(?kl_v_a = ?kl_v_a_temp, ?kl_v_aURI_temp, ?undefined) AS ?kl_v_aURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/207645b8f83b536f8f2984bd98972a2e> ?kl_v_gdURI_temp .  # ?objectURI ?VColorGDProperty ?kl_v_gdURI_temp . ?VColorGDProperty skos:prefLabel "V color GD" .
    OPTIONAL {
      ?kl_v_gdURI_temp skos:prefLabel ?kl_v_gd_temp .
    }
    BIND( COALESCE(?kl_v_gd_temp, ?kl_v_gdURI_temp) AS ?kl_v_gd) .
    BIND( IF(?kl_v_gd = ?kl_v_gd_temp, ?kl_v_gdURI_temp, ?undefined) AS ?kl_v_gdURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/9df34a271d37ea19cda9171dd1b95438> ?kl_v_gnURI_temp .  # ?objectURI ?VColorGNProperty ?kl_v_gnURI_temp . ?VColorGNProperty skos:prefLabel "V color GN" .
    OPTIONAL {
      ?kl_v_gnURI_temp skos:prefLabel ?kl_v_gn_temp .
    }
    BIND( COALESCE(?kl_v_gn_temp, ?kl_v_gnURI_temp) AS ?kl_v_gn) .
    BIND( IF(?kl_v_gn = ?kl_v_gn_temp, ?kl_v_gnURI_temp, ?undefined) AS ?kl_v_gnURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/095f7786fa03ee5d1fb5a5f76a93eb5e> ?kl_v_vURI_temp .  # ?objectURI ?VColorVProperty ?kl_v_vURI_temp . ?VColorVProperty skos:prefLabel "V color V" .
    OPTIONAL {
      ?kl_v_vURI_temp skos:prefLabel ?kl_v_v_temp .
    }
    BIND( COALESCE(?kl_v_v_temp, ?kl_v_vURI_temp) AS ?kl_v_v) .
    BIND( IF(?kl_v_v = ?kl_v_v_temp, ?kl_v_vURI_temp, ?undefined) AS ?kl_v_vURI) .

    ?objectURI <http://digitalbuildingdata.tech/nlcs/def/965ac85b41943c884f3487cb131e05bd> ?lt_vURI .  # ?objectURI ?VLinetypeProperty ?lt_vURI . ?VLinetypeProperty skos:prefLabel "V linetype" .
    ?lt_vURI skos:prefLabel ?lt_v .
  } 
  
} ORDER BY ?id
