PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>

# Retrieves all Lijntype information and stores it in the familiar Excel/CSV format from the SQL database

SELECT DISTINCT ?lijntypeURI ?id ?hoofdgroep ?omschrijving ?finalCleanName ?fase ?optie ?autocaddef 
WHERE {
  ?LijntypeTopConcept a owl:Class .
  ?LijntypeTopConcept skos:prefLabel "Lijntype" .
  ?Hoofdgroep rdfs:subClassOf ?LijntypeTopConcept .
  ?Hoofdgroep skos:prefLabel ?HoofdgroepName .
  ?lijntypeURI rdfs:subClassOf* ?Hoofdgroep .
  ?lijntypeURI skos:prefLabel ?omschrijving .
  BIND ( IF(?lijntypeURI = ?Hoofdgroep, IF(?omschrijving IN ("V-CONTINUOUS-SO", "CONTINUOUS", "NLCS_HIDDEN-SO"), ?lijntypeURI, ?undefined), ?lijntypeURI) AS ?NotHoofdgroep) .
  BIND ( IF(?lijntypeURI = ?Hoofdgroep, IF(?omschrijving IN ("V-CONTINUOUS-SO", "CONTINUOUS", "NLCS_HIDDEN-SO"), ?undefined, ?HoofdgroepName), ?HoofdgroepName) AS ?hoofdgroep) .
  FILTER (?lijntypeURI = ?NotHoofdgroep) .
  OPTIONAL {
    ?lijntypeURI ?optieProperty ?optie .
    ?optieProperty skos:prefLabel "Optie" .
  } OPTIONAL {
    ?lijntypeURI ?idProperty ?id .
    ?idProperty skos:prefLabel "ID" .
  } OPTIONAL {
    ?lijntypeURI skos:definition ?autocaddef .
  } OPTIONAL {
    ?lijntypeURI ?faseProperty ?fase .
    ?faseProperty skos:prefLabel "Fase" .
  }

  BIND (IF (
            (BOUND(?fase) && CONTAINS(?omschrijving, ?fase)), 
            SUBSTR(REPLACE(?omschrijving, ?fase, ""), 2),
            ?omschrijving) AS ?nameWithoutFase)

  BIND( IF(BOUND(?nameWithoutFase), STRLEN(?nameWithoutFase)-1, STRLEN(?omschrijving)-1) AS ?len)
  
  BIND(
    IF(
      BOUND(?nameWithoutFase),
      IF(
        BOUND(?hoofdgroep) && CONTAINS(?nameWithoutFase, ?hoofdgroep),
        SUBSTR(REPLACE(?nameWithoutFase, ?hoofdgroep, ""), 2),
        ?nameWithoutFase
      ),
      IF(
        BOUND(?hoofdgroep) && CONTAINS(?omschrijving, ?hoofdgroep),
        SUBSTR(REPLACE(?omschrijving, ?hoofdgroep, ""), 2),
        ?omschrijving 
      )
    ) AS ?nameWithoutFaseHoofdgroep
  )

  BIND( IF(BOUND(?nameWithoutFaseHoofdgroep), 
          STRLEN(?nameWithoutFaseHoofdgroep)-1, 
          IF(BOUND(?nameWithoutFase), STRLEN(?nameWithoutFase)-1, STRLEN(?omschrijving)-1)
          ) AS ?len2)
  
  BIND(
    IF(
      BOUND(?nameWithoutFaseHoofdgroep),
      IF(
        BOUND(?optie) && CONTAINS(?nameWithoutFaseHoofdgroep, ?optie),
        SUBSTR(REPLACE(?nameWithoutFaseHoofdgroep, ?optie, ""), 1, (?len2 - strlen(?optie))),
        ?nameWithoutFaseHoofdgroep
      ),
      IF(
        BOUND(?nameWithoutFase),
        IF( BOUND(?optie) && CONTAINS(?nameWithoutFase, ?optie),
            SUBSTR(REPLACE(?nameWithoutFase, ?optie, ""), 1, (?len2 - strlen(?optie))),
            ?nameWithoutFase
        ),
        IF(
          BOUND(?optie) && CONTAINS(?omschrijving, ?optie),
          SUBSTR(REPLACE(?omschrijving, ?optie, ""), 1, (?len2 - strlen(?optie))),
          ?omschrijving 
        )
      )
    ) AS ?finalCleanName
  )

  # BIND (IF (
  #           (BOUND(?fase) && CONTAINS(?omschrijving, ?fase)), 
  #           SUBSTR(REPLACE(?omschrijving, ?fase, ""), 2),
  #           ?omschrijving) AS ?nameWithoutFase)

  # BIND( IF(BOUND(?nameWithoutFase), STRLEN(?nameWithoutFase)-1, STRLEN(?omschrijving)-1) AS ?len)
  
  # BIND(
  #   IF(
  #     BOUND(?nameWithoutFase),
  #     IF(
  #       BOUND(?optie) && CONTAINS(?nameWithoutFase, ?optie),
  #       SUBSTR(REPLACE(?nameWithoutFase, ?optie, ""), 1, (?len - strlen(?optie))),
  #       ?nameWithoutFase
  #     ),
  #     IF(
  #       BOUND(?optie) && CONTAINS(?omschrijving, ?optie),
  #       SUBSTR(REPLACE(?omschrijving, ?optie, ""), 1, (?len - strlen(?optie))),
  #       ?omschrijving 
  #     )
  #   ) AS ?finalCleanName
  # )

} ORDER BY ?id
