copy bijschriften.html ..\..\..\waterbouw\richtlijnen\algemeen\bijschriften.html
copy bijschriften.html ..\..\..\wegen\richtlijnen\algemeen\bijschriften.html
copy tekst.html ..\..\..\waterbouw\richtlijnen\algemeen\tekst.html
copy tekst.html ..\..\..\wegen\richtlijnen\algemeen\tekst.html
copy tekst_AutoCAD.html ..\..\..\waterbouw\richtlijnen\algemeen\tekst_AutoCAD.html
copy tekst_AutoCAD.html ..\..\..\wegen\richtlijnen\algemeen\tekst_AutoCAD.html
copy cc.pdf ..\..\..\waterbouw\richtlijnen\algemeen\cc.pdf
copy cc.pdf ..\..\..\wegen\richtlijnen\algemeen\cc.pdf
copy overzicht_font.html ..\..\..\waterbouw\richtlijnen\algemeen\overzicht_font.html
copy overzicht_font.html ..\..\..\wegen\richtlijnen\algemeen\overzicht_font.html
copy kader.html ..\..\..\waterbouw\richtlijnen\algemeen\kader.html
copy kader.html ..\..\..\wegen\richtlijnen\algemeen\kader.html
copy kader_AutoCAD.html ..\..\..\waterbouw\richtlijnen\algemeen\kader_AutoCAD.html
copy kader_AutoCAD.html ..\..\..\wegen\richtlijnen\algemeen\kader_AutoCAD.html
copy lijnen.html ..\..\..\waterbouw\richtlijnen\algemeen\lijnen.html
copy lijnen.html ..\..\..\wegen\richtlijnen\algemeen\lijnen.html
copy lijnen_AutoCAD.html ..\..\..\waterbouw\richtlijnen\algemeen\lijnen_AutoCAD.html
copy lijnen_AutoCAD.html ..\..\..\wegen\richtlijnen\algemeen\lijnen_AutoCAD.html
