PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>

# Checks uniqueness of ID property of Arcering

SELECT DISTINCT ?abibliotheekURI ?id ?abibliotheek ?omschrijving
WHERE {
  ?ArceringTopConcept a owl:Class .
  ?ArceringTopConcept skos:prefLabel "Arcering" .
  ?abibliotheekURI rdfs:subClassOf ?ArceringTopConcept .
  ?abibliotheekURI skos:prefLabel ?abibliotheek .
  ?abibliotheekURI skos:definition ?omschrijving .
  ?idProperty skos:prefLabel "ID" . 
  OPTIONAL { ?abibliotheekURI ?idProperty ?id . }
       
  FILTER(!BOUND(?id) || (STRLEN(STR(?id)) =0) ) .
} ORDER BY ?id