PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>

# check: if there is only 1 arcering connected directly to the nlcs object

SELECT ?omschrijving ?aobject ?aobject2

WHERE {
  ?NLCSObjectTopConcept a owl:Class .
  ?NLCSObjectTopConcept skos:prefLabel "NLCS-object" .
  ?hoofdgroepURI rdfs:subClassOf ?NLCSObjectTopConcept .
  ?hoofdgroepURI skos:prefLabel ?hoofdgroep .
  ?objectURI rdfs:subClassOf+ ?hoofdgroepURI .
  ?objectURI skos:prefLabel ?omschrijving .
  
    ?objectURI rdfs:subClassOf ?bnodeArcering .
    ?bnodeArcering owl:onProperty <https://w3id.org/nen2660/def#isDescribedBy> .
    ?bnodeArcering owl:onClass ?aobjectURI .
    ?ArceringTopConcept skos:prefLabel "Arcering" .
    ?aobjectURI rdfs:subClassOf* ?ArceringTopConcept .
    ?aobjectURI skos:prefLabel ?aobject .

    ?objectURI rdfs:subClassOf ?bnodeArcering2 .
    ?bnodeArcering2 owl:onProperty <https://w3id.org/nen2660/def#isDescribedBy> .
    ?bnodeArcering2 owl:onClass ?aobjectURI2 .
    ?aobjectURI2 rdfs:subClassOf* ?ArceringTopConcept .
    ?aobjectURI2 skos:prefLabel ?aobject2 .

    FILTER(?aobjectURI != ?aobjectURI2)
  
} ORDER BY ?omschrijving