PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>

# Retrieves all Discipline information and stores it in the familiar Excel/CSV format from the SQL database

SELECT DISTINCT ?disciplineURI ?id ?code ?verklaring ?omschrijving
WHERE {
  ?DisciplineTopConcept skos:prefLabel "Disciplines" .
  ?disciplineURI a ?DisciplineTopConcept .
  ?disciplineURI skos:prefLabel ?code .
  ?disciplineURI skos:altLabel ?verklaring .
  ?disciplineURI skos:definition ?omschrijving .
  OPTIONAL {
    ?disciplineURI ?idProperty ?id .
    ?idProperty skos:prefLabel "ID" .
  }
  FILTER((!BOUND(?id) || (STRLEN(STR(?id)) = 0)) 
        || 
        (!BOUND(?code) || (STRLEN(STR(?code)) = 0)) 
        || 
        (!BOUND(?omschrijving) || (STRLEN(STR(?omschrijving)) = 0)) 
        || 
        (!BOUND(?verklaring) || (STRLEN(STR(?verklaring)) = 0))
        )
} ORDER BY ?id