PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>

# Check if ID is unique within the category

SELECT DISTINCT ?abibliotheekURI ?abibliotheekURI2 ?arceringURI ?arceringURI2 ?disciplineURI ?disciplineURI2 ?hoofdgroepURI ?hoofdgroepURI2 ?lijnkleurURI ?lijnkleurURI2 ?sbibliotheekURI ?sbibliotheekURI2 ?symboolURI ?symboolURI2
WHERE {
    ?idProperty skos:prefLabel "ID" . 

    # Check for Abibliotheek and Arcering
    ?ArceringTopConcept a owl:Class .
    ?ArceringTopConcept skos:prefLabel "Arcering" .
    ?abibliotheekURI rdfs:subClassOf ?ArceringTopConcept .
    ?abibliotheekURI2 rdfs:subClassOf ?ArceringTopConcept .
    ?abibliotheekURI ?idProperty ?idAbibliotheek .
    ?abibliotheekURI2 ?idProperty ?idAbibliotheek .
    FILTER(?abibliotheekURI != ?abibliotheekURI2) .

    ?arceringURI rdfs:subClassOf+ ?abibliotheekURI .
    ?arceringURI2 rdfs:subClassOf+ ?abibliotheekURI .
    FILTER( NOT EXISTS { ?subArcering rdfs:subClassOf ?arceringURI . }) .
    FILTER( NOT EXISTS { ?subArcering rdfs:subClassOf ?arceringURI2 . }) .
    ?arceringURI ?idProperty ?idArcering .
    ?arceringURI2 ?idProperty ?idArcering .
    FILTER(?arceringURI != ?arceringURI2) 

    #Check for discipline
    ?DisciplineTopConcept skos:prefLabel "Disciplines" .
    ?disciplineURI a ?DisciplineTopConcept .
    ?disciplineURI2 a ?DisciplineTopConcept .
    ?disciplineURI ?idProperty ?idDiscipline .
    ?disciplineURI2 ?idProperty ?idDiscipline .
    FILTER(?disciplineURI != ?disciplineURI2) 

    ?NLCSObjectTopConcept a owl:Class .
    ?NLCSObjectTopConcept skos:prefLabel "NLCS-object" .
    ?hoofdgroepURI rdfs:subClassOf ?NLCSObjectTopConcept .
    ?hoofdgroepURI2 rdfs:subClassOf ?NLCSObjectTopConcept .
    ?hoofdgroepURI ?idProperty ?idHoofdgroep .
    ?hoofdgroepURI2 ?idProperty ?idHoofdgroep .
    FILTER(?hoofdgroepURI != ?hoofdgroepURI2)

    ?LijnkleurTopConcept a owl:Class .
    ?LijnkleurTopConcept skos:prefLabel "Lijnkleur" . 
    ?lijnkleurURI rdfs:subClassOf ?LijnkleurTopConcept .
    ?lijnkleurURI2 rdfs:subClassOf ?LijnkleurTopConcept .
  	?lijnkleurURI ?idProperty ?idLijnkleur .
  	?lijnkleurURI2 ?idProperty ?idLijnkleur .
    ?idProperty skos:prefLabel "ID" .
    FILTER(?lijnkleurURI != ?lijnkleurURI2)

    ?SymboolTopConcept a owl:Class .
    ?SymboolTopConcept skos:prefLabel "Symbool" .
    ?sbibliotheekURI rdfs:subClassOf ?SymboolTopConcept .
    ?sbibliotheekURI2 rdfs:subClassOf ?SymboolTopConcept .
    ?sbibliotheekURI ?idProperty ?idSbibliotheek .
    ?sbibliotheekURI2 ?idProperty ?idSbibliotheek .
    FILTER(?sbibliotheekURI != ?sbibliotheekURI2)

    ?SymboolTopConcept a owl:Class .
    ?SymboolTopConcept skos:prefLabel "Symbool" .
    ?sbibliotheekURI rdfs:subClassOf ?SymboolTopConcept .
    ?symboolURI rdfs:subClassOf+ ?sbibliotheekURI .
    FILTER (NOT EXISTS{?subSymbool rdfs:subClassOf ?symboolURI}) .  
    ?symboolURI ?idProperty ?idSymbool .
    ?symboolURI2 rdfs:subClassOf+ ?sbibliotheekURI .
    FILTER (NOT EXISTS{?subSymbool rdfs:subClassOf ?symboolURI2}) .  
    ?symboolURI2 ?idProperty ?idSymbool .
    FILTER(?symboolURI != ?symboolURI2)
}