PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>

SELECT DISTINCT ?objectURI ?hoofdgroepURI ?hoofdgroep ?id_nummer ?lt_v ?omschrijving ?lijntypeOmschrijving ?autocaddef
WHERE {
  ?NLCSObjectTopConcept a owl:Class .
  ?NLCSObjectTopConcept skos:prefLabel "NLCS-object" .
  ?hoofdgroepURI rdfs:subClassOf ?NLCSObjectTopConcept .
  ?hoofdgroepURI skos:prefLabel ?hoofdgroep .
  ?objectURI rdfs:subClassOf+ ?hoofdgroepURI .
  ?objectURI skos:prefLabel ?omschrijving .

  OPTIONAL {
    ?objectURI ?idProperty ?id_nummer .
    ?idProperty skos:prefLabel "ID" .
  }

  OPTIONAL {
    ?objectURI ?VLinetypeProperty ?lt_vURI .
    ?VLinetypeProperty skos:prefLabel "V linetype" .
    ?lt_vURI skos:prefLabel ?lt_v .

    ?lt_vURI skos:prefLabel ?lijntypeOmschrijving .
    ?lt_vURI skos:definition ?autocaddef .
  }

  FILTER(CONTAINS(LCASE(STR(?autocaddef)), "verwijderen")) # filtert alleen lijntypes met "verwijderen" in de AutoCAD-definitie
}
