PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX nen2660: <https://w3id.org/nen2660/def#>

SELECT DISTINCT ?conceptUri ?conceptNaam ?propertyUri ?propertyNaam ?propertyWaarde
WHERE {
    ?conceptUri a owl:Class .
    FILTER(!CONTAINS(STR(?conceptUri), "nen2660")) .
    ?conceptUri skos:prefLabel ?conceptNaam .
    ?conceptUri rdfs:subClassOf ?bnode .
    ?bnode owl:onProperty ?propertyUri .
    ?propertyUri skos:prefLabel ?propertyNaam .
    OPTIONAL {
        ?bnode owl:hasValue/skos:prefLabel ?propertyWaarde .
    }
}