;;*****************************************
;;  Nederlandse Cadstandaard NLCS  
;;  versie 2, feb 2010             
;;  Auteur: Nauk van der Donk      
;;                                 
;;*****************************************

*AVH-TEGEL_400X400_HALFST,tegels 400x400 halfsteensverband
0.0 , 0.0  , 0.0  , 0.0, .4000
90.0, 0.0  , 0.0  , 0.0, .4000, .4000, -.4000
90.0, .20, .4000, 0.0, .4000, .4000, -.4000
