;;*****************************************
;;  Nederlandse Cadstandaard NLCS  
;;  versie 2, feb 2010             
;;  Auteur: Nauk van der Donk      
;;                                 
;;*****************************************

*AVH-TEGEL_500X500_HALFST,tegels 400x400 halfsteensverband
0.0 , 0.0  , 0.0  , 0.0, .5000
90.0, 0.0  , 0.0  , 0.0, .5000, .5000, -.5000
90.0, .20, .5000, 0.0, .5000, .5000, -.5000
