PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# Retrieves all general Hoofdgroep information and stores it in the familiar Excel/CSV format

SELECT distinct ?hoofdgroup_name 

WHERE {
  ?NLCSObjectTopConcept a owl:Class .
  ?NLCSObjectTopConcept skos:prefLabel "NLCS-object" .
  ?HOOFDGROEP rdfs:subClassOf ?NLCSObjectTopConcept .
  ?HOOFDGROEP skos:prefLabel ?hoofdgroup_name .
} order by ?hoofdgroup_name
